[package]
name = "rustic_ml"
version = "0.0.0"
authors = ["Kjetil Indrehus <kjetilindrehus@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
